### ISSUE TITLE
Genome mapping

### ISSUE THREAD

**Issue by al3xMlt** [GoekeLab/m6anet#10]
Hello,
thanks for your tool to detect m6a! 
Is it possible to map the modifications to the genome? (like in xpore through using the genome flag in the dataprep step)? 
Or is it only possible on the isoformlevel? 

Big thanks!

**Comment by chrishendra93** [comment]
hi @al3xMlt , sorry for the late response,

It should be possible if you provide nanopolis eventalign.txt that is already in genomic coordinates
