### ISSUE TITLE
m6anet inference result format 

### ISSUE THREAD

**Issue by sunsetyerin** [GoekeLab/m6anet#100]
I'm getting m6anet inference table with the following result called  **data.result.csv.gz**

'''
transcript_id,transcript_position,n_reads,probability_modified,kmer
ENST00000611116,9,95,0.17386298,GAACC
ENST00000611116,15,90,0.33967417,TGACC
ENST00000611116,39,90,0.5680754,AGACT
ENST00000611116,54,76,0.5067585,TGACA
ENST00000611116,92,92,0.0128501775,AAACA
'''

_**I wonder how can I get "data.indiv_proba.csv" result?**_ 

These files are **m6anet_dataprep** directory includes (This is different from m6anet documentation so kind of confusing too)
data.index
data.json
data.log
data.readcount
eventaling.index

This is how eventalign.txt looks like 
'''
contig  position        reference_kmer  read_index      strand  event_index     event_level_mean        event_stdv      event_length    model_kmer      model_mean      model_stdv      standardized_level      start_idx       end_idx
ENST00000611116.2       0       ATATC   0       t       1347    86.91   3.681   0.00267 ATATC   83.15   2.63    1.18    63711   63719
ENST00000611116.2       0       ATATC   0       t       1348    79.40   2.186   0.00233 ATATC   83.15   2.63    -1.18   63704   63711
ENST00000611116.2       0       ATATC   0       t       1349    84.75   3.699   0.00567 ATATC   83.15   2.63    0.50    63687   63704
ENST00000611116.2       0       ATATC   0       t       1350    80.07   2.174   0.00700 ATATC   83.15   2.63    -0.97   63666   63687
ENST00000611116.2       1       TATCC   0       t       1351    87.99   6.781   0.00233 TATCC   94.26   5.70    -0.91   63659   63666
'''

**Comment by chrishendra93** [comment]
hi @sunsetyerin , as I have mentioned in Issue #98 , you cannot get data.indiv_proba.csv because you are using the version of m6anet that does not have that functionality. Can you try the one from github or the latest m6anet version from pypi instead?

Thanks!
