### ISSUE TITLE
pip install error for m6anet==2.0.1

### ISSUE THREAD

**Issue by Stakaitis** [GoekeLab/m6anet#101]
An error occurs when trying to install the lates version of m6Anet
`pip install m6anet==2.0.1`

Error:

> ERROR: Could not find a version that satisfies the requirement torch==1.6.0 (from m6anet) (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0)
ERROR: No matching distribution found for torch==1.6.0

**Comment by Stakaitis** [comment]
The problem was the python version in my environment:

> python-3.9.16-h2782a2a_0_cpython

The required [Torch version 1.6.0](https://download.pytorch.org/whl/torch_stable.html) does not have a support for Python 3.9. It only supports Python from 3.6 to 3.8, which can be seen when searching for _torch-1.6.0_ in the provided link, and noticing the python version abbreviation in the _.whl_ name: cp36, cp37, cp38

This installation issue can be resolved by creating a new conda environment with a python 3.8 and installing m6Anet through pip:

`conda create --name m6anet python=3.8
conda activate m6anet
pip install m6anet==2.0.1`

Probably, the installation instructions should be edited

**Comment by chrishendra93** [comment]
hi @Stakaitis , thanks for reporting this. There was a problem when I tried to run m6anet on the newer version of torch, that is why I specify the torch version to 1.6.0 which works out just fine for m6anet. I will look into this and hopefully with the new release, we can support newer python version
