### ISSUE TITLE
installation issue on the 2.0.1 version

### ISSUE THREAD

**Issue by eltonjrv** [GoekeLab/m6anet#109]
Dear m6anet folks,

When attempting to install the latest version (pip install m6anet==2.0.1), despite having numpy 1.24 in my conda environment designated to this m6anet installation, it retrocedes to numpy 1.18, and finishes with the following error message:

   note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed cleaning build dir for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]

Any clue to solve this?
Thanks very much

**Comment by chrishendra93** [comment]
hi @eltonjrv sorry for the delay in my reply. May I know which Python version you are using and if you're building this in a conda environment?

**Comment by eltonjrv** [comment]
Hi Chris,

It's python 3.11, and yes, through conda.

Thanks

**Comment by chrishendra93** [comment]
hi @eltonjrv,

try downgrading python to 3.7 and 3.8 and reinstall m6anet. Some error has been reported for python 3.9 as well https://github.com/GoekeLab/m6anet/issues/101, which in that case was due to pytorch version

**Comment by eltonjrv** [comment]
Sorry, completely forgot to reply on the day.
Yes, downgrading to python 3.7 solved the issue.
Thanks
