### ISSUE TITLE
Difference between mod_ratio and probability_modified

### ISSUE THREAD

**Issue by acarmas1** [GoekeLab/m6anet#118]
Hello,

I've used your software to detect m6A sites, and to report my results I'm a little confused of what is the difference between the modification ratio and the modification probability. 

Please if you could explain it better for me. I'll appreciate it. 

Thanks,
Camila

**Comment by chrishendra93** [comment]
hi @acarmas1 please refer to discussion #114. Let me know if this is not clear

Thanks!
