### ISSUE TITLE
change the number of read count

### ISSUE THREAD

**Issue by Lqh09** [GoekeLab/m6anet#13]
Hi, how to change the minimum read count when running m6anet-run_inference? Thanks!

**Comment by Lqh09** [comment]
I want to decrease the number of supporting reads to find more m6A modified sites.

**Comment by chrishendra93** [comment]
hi @Lqh09, currently I haven't implemented the functionality to do this. You can probably adjust the model file itself in pooling_blocks.py but I do not recommend this since we probably have to retrain the model
