### ISSUE TITLE
transcript_position column header from data.site_proba.csv output file

### ISSUE THREAD

**Issue by gsukrit** [GoekeLab/m6anet#130]
Hi team, 

I would like to have clarity on the column header _transcript_position_ in the output file of _data.site_proba.csv__ generated after the command _m6anet inference_. Does it indicate the position of modified base from the start of that particular transcript ID or the coordinate on the genome where that modified base is predicted. If it is the position of the base from the start of that particular transcript, does it start from the mRNA coordinates (starting from the 5' UTR region) on the genome ?

Any idea on this concern further will be highly appreciated.

Thanks, 

Sukriti

**Comment by kristinrma** [comment]
Hi @gsukrit,
The former is correct- the coordinates are relative to the specific transcript not the genome. The transcript position indicates the position of the modified base relative to the start of the 5’ end of that particular transcript. Discussion #104  gives further details on mapping between transcript and genome coordinates if you are interested.
