### ISSUE TITLE
Identification of m6A with the SG-NEx samples

### ISSUE THREAD

**Issue by VikArz02** [GoekeLab/m6anet#139]
Hello! I want to explore m6Anet using the SG-NEx dataset with preprocessed data for m6Anet. However, it appears that this dataset lacks the data.info component. Could you please guide how I can effectively utilize this dataset to experiment with m6Anet? Thank you for your assistance.

**Comment by VikArz02** [comment]
And if i rename readcount to info, i had the error with index: KeyError: "['start', 'end'] not in index"

**Comment by kristinrma** [comment]
Hi @VikArz02,

Apologies for the outdated m6Anet preprocessed files; we will be updating them on the next SG-NEx release. For now you can use this script that appends the 'n_reads' column of data.readcount to data.index to create data.info. It will contain the same information as if you generated data.info from m6Anet dataprep.

import pandas as pd

def create_data_info(data_index, data_readcount, data_info):
    index_df = pd.read_csv(data_index)
    readcount_df = pd.read_csv(data_readcount)
    index_df = index_df.join(readcount_df['n_reads'], how='right')
    index_df.to_csv(data_info, index=False)

create_data_info('data.index', 'data.readcount', 'data.info')

**Comment by VikArz02** [comment]
I found way from command line that you recommended in your release 2.0.0: m6anet convert. Thank you for the fast answer!

**Comment by kristinrma** [comment]
No problem!
