### ISSUE TITLE
NUM_NEIGHBORING_FEATURES

### ISSUE THREAD

**Issue by al3xMlt** [GoekeLab/m6anet#14]
Hey Christoph,
Thanks a lot for the tool. 
have you played around using different NUM_NEIGHBORING_FEATURES for extracting during dataprep? 
Are they interesting results?

Best

-Alex

**Comment by chrishendra93** [comment]
hi @al3xMlt , 

I have played around with different NUM_NEIGHBORING_FEATURES and found that 1 neighboring feature gives the best performance for m6Anet so far. This information will be available on the pre-print which hopefully will be out in the next week or two

Thanks!

Regards

Christopher Hendra

**Comment by al3xMlt** [comment]
Hey Christopher,
As I am currently writing my master's thesis and using your tool, I am really looking forward to reading the preprint. I would still be very happy if you could find the time to answer a few questions that I still need for my thesis. Would be really cool if we can discuss this further by email maybe? 

Regards 
Alex

**Comment by chrishendra93** [comment]
Hi @al3xMlt ,

Yes sure, we can discuss this further by email!

**Comment by al3xMlt** [comment]
Maybe you can just drop your mail or give me a short text on: alexander.malt@mdc-berlin.de
