### ISSUE TITLE
Memory usage exploding

### ISSUE THREAD

**Issue by mnsmar** [GoekeLab/m6anet#150]
Hi,

The memory usage is exploding during `m6anet data_prep` and the run is killed. Any idea what's causing this? Here is the command I use:

```
m6anet dataprep --eventalign eventalign.txt --out_dir ouput --readcount_max 1000000 --n_processes 10
```

<img width="778" alt="image" src="https://github.com/GoekeLab/m6anet/assets/1588709/78c6b4a1-4f50-4304-b272-d308cf82ce69">

**Comment by yuukiiwa** [comment]
Hi @mnsmar,

This memory explosion was likely due to `--readcount_max  10000000`. You can try using the default `--readcount_max`, which is 1000.

Thanks!

Best wishes,
Yuk Kei

**Comment by yuukiiwa** [comment]
Hi @mnsmar,

Thanks for the explanation of your data! 

Given that most reads are of the same sites, you can consider splitting them into smaller `eventalign.txt` files and run `m6anet dataprep` separately on them.

Thanks!

Best wishes,
Yuk Kei
