### ISSUE TITLE
Questions about the m6A motif

### ISSUE THREAD

**Issue by Songmg-Nwafu** [GoekeLab/m6anet#153]
Hi, thanks for so good job! But I wonder if m6Anet can only detect m6A modifications of DRACH motif using Arabidopsis Trained Model. Thank you!

**Comment by yuukiiwa** [comment]
Hi @Songmg-Nwafu,

Yes, `m6anet` only supports DRACH motifs for all models.

Thanks!

Best wishes,
Yuk Kei
