### ISSUE TITLE
TypeError: argument should be integer or None, not 'numpy.float64'

### ISSUE THREAD

**Issue by rugilemat** [GoekeLab/m6anet#160]
Hi,
I've been able to run m6anet 2.1.0 without any issues. However, it suddenly started failing with `TypeError: argument should be integer or None, not 'numpy.float64'` when running `m6anet inference` on HPC.

My command is as follows:
`m6anet inference --input_dir ${input} --out_dir ${output} --pretrained_model HEK293T_RNA004 --n_processes 20 --num_iterations 5`

I had m6anet installed through `pip` but the same error persists when running a `conda` installed version. My python version is 3.8.

I'm not entirely sure if it's something that's failing on our HPC end or something else is going on, so any advice would be greatly appreciated!

**Comment by yuukiiwa** [comment]
Hi @rugilemat,

Can you try removing --num_iterations 5 from your command and see whether that solves the problem?

```
m6anet inference --input_dir ${input} --out_dir ${output} --pretrained_model HEK293T_RNA004 --n_processes 20
```

Thanks!

Best wishes,
Yuk Kei

**Comment by rugilemat** [comment]
Hi @yuukiiwa,

Thanks for this! I think the issue was with the files generated from `m6anet dataprep` as I didn't have this issue with a different dataset and rerunning `m6anet dataprep` on the file that was producing the issue solved it. If I encounter something similar next time, I'll try dropping `--num_iterations 5 `.
