### ISSUE TITLE
Interpreting 'inference' results

### ISSUE THREAD

**Issue by DattaSujayAyyagari** [GoekeLab/m6anet#161]
First of all I would like to thank the authors for their noble work in the field of RNA modifications. 

I am trying to understand the results obtained from 'inference' for the default model. 

transcript_id	transcript_position	n_reads	probability_modified	kmer	mod_ratio
NC_006998.1	7305	20	0.475717663764954	AAACA	0.1
NC_006998.1	7314	21	0.0174570530653	AAACA	0
NC_006998.1	7501	31	0.264436513185501	TGACT	0.193548387096774
NC_006998.1	7591	39	0.03686386346817	AGACT	0
NC_006998.1	7609	36	0.017043016850948	AAACC	0
NC_006998.1	7615	34	0.019228557124734	AAACA	0
NC_006998.1	7719	37	0.756251752376556	GAACT	0.45945945945946
NC_006998.1	7724	32	0.07085482776165	AAACT	0.03125
NC_006998.1	92119	21	0.019832568243146	AAACA	0
NC_006998.1	92211	22	0.125267326831818	GAACC	0.045454545454546
NC_006998.1	92270	25	0.31541308760643	TGACC	0.16
NC_006998.1	92379	25	0.010519345290959	AGACA	0
NC_006998.1	92395	25	0.091122098267078	TGACT	0
NC_006998.1	92467	25	0.011478235013783	AAACT	0
NC_006998.1	92511	25	0.089275971055031	AAACT	0.04
NC_006998.1	144500	20	0.080855697393417	TGACT	0.05

Commands used : m6anet inference --output_dir /path/to/output --input_dir /path/to/output --n_processes 4 --num_iterations 1000

Is 0.9 a hard cut-off criterion to predict m6a sites or is 0.9 to be used as --read_proba_threshold when giving the command. 

Based on my understanding I assume we should look for sites which have 0.9 or above probability_modified in the data.indiv_proba.csv but some more explanation, to infer the results, would be very helpful.

Thank you.

**Comment by yuukiiwa** [comment]
Hi @DattaSujayAyyagari,

0.9 is not a hard cut-off for m6A sites. For our publications, we found 0.9 to be a reasonable threshold for the site likely being m6A. We do not supply the `--read_proba_threshold 0.9` argument when running `m6anet`.

For read-level prediction, you can interpret reads with a probability_modified > 0.9 in the `data.indiv_proba.csv` file as predicted m6A sites. For site-level prediction, similarly, you can interpret sites with a probability_modified > 0.9 in the `data.site_proba.csv` as predicted m6A sites. The mod_ratio provided in the `data.site_proba.csv` is the fraction of the reads being predicted modified.

Thanks!

Best wishes,
Yuk Kei
