### ISSUE TITLE
m6anet dataprep fails to complete: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by nmichaels89** [GoekeLab/m6anet#162]
Hi, while running dataprep, it exits with this error:
```
Process Consumer-7:
Traceback (most recent call last):
  File "/home/exouser/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/exouser/.pyenv/versions/3.8.0/lib/python3.8/site-packages/m6anet/utils/helper.py", line 85, in run
    result = self.task_function(*next_task_args,self.locks)
  File "/home/exouser/.pyenv/versions/3.8.0/lib/python3.8/site-packages/m6anet/utils/dataprep_utils.py", line 206, in index
    f_index.write('%s,%d,%d,%d\n' %(transcript_id,read_index,pos_start,pos_end))
ValueError: cannot convert float NaN to integer
```
I saw that there was a previous issue about this but didn't understand the follow up. I can't identify any NaN in the eventalign.txt file, so I'm not sure what to do.

**Comment by yuukiiwa** [comment]
Hi @nmichaels89,

Can you share the first 100 lines of your `eventalign.txt` and put it here, so that I can see whether I can reproduce your error.

Other than that, can you tell me which computer system (windows, mac, or linux), python version, and numpy version you have on your computer?

Thanks!

Best wishes,
Yuk Kei

**Comment by nmichaels89** [comment]
Hi Yuk,

Thank you for the fast response. I have attached the first 100 lines of eventalign.txt as a file:
[100lea.txt](https://github.com/GoekeLab/m6anet/files/14827426/100lea.txt)
I might add that dataprep runs for some time before quitting, with the eventalign.index reaching 585250 lines, ending as such:
```

NC_020455.1,701979,47499572492,47499711425
NC_020455.1,701976,47499711515,47500057705
55.1,701976,47500057705,47500057791

```
I am accessing a vm running Linux 5.15.0-101-generic x86_64 from a Macbook using terminal.
Python version: 3.8.0 (via pyenv due to failure to installation failures on modern python)
Numpy version: 1.24.4

I appreciate any help you can offer!

Thanks,
Nat

**Comment by nmichaels89** [comment]
Hi,
I looked into it further by modifying the python script to throw a more detailed error, and it turns out that there was a line of text in my eventalign.txt. I'm not sure how it got in there, but that was the issue. I removed it and everything seems to be working fine.
Thanks!
