### ISSUE TITLE
The position output by m6anet seems to be 1 less than the actual position

### ISSUE THREAD

**Issue by wfy1373** [GoekeLab/m6anet#164]
Dear m6anet team,

I have encountered an issue while using your tool and analyzing the output data.site_proba.csv file. It appears the transcript_position values reported in the output are off by 1 compared to the actual position of the m6A sites.
For example, one row in the data.site_proba.csv file is:
ENST00000361453.3,716,28,0.3540786206722260,TGACT,0.2142857142857143
However, the actual position of the A should be 717, not 716.

I wanted to confirm if this observation is correct, is this because m6anet uses 0-based indexing to report the position coordinates?

Thank you in advance for your assistance.

Sincerely,
wfy

**Comment by yuukiiwa** [comment]
Dear @wfy1373,

Yes, `m6anet` is 0-based, so it is normal for the positions to be off by one.

Thanks! 

Best wishes,
Yuk Kei
