### ISSUE TITLE
probability_modified and mod_ratio are 0

### ISSUE THREAD

**Issue by lbwfff** [GoekeLab/m6anet#168]
Dear Developer

I was recently trying to analyze one of the HEK293T datasets using m6anet and I have some questions about the results. Some of the sites in the results file have 0 for both probability_modified and mod_ratio as shown in the figure below for example
![Screenshot 2024-07-05 at 12 58 35 PM](https://github.com/GoekeLab/m6anet/assets/74947198/e5f9974f-1ef7-49c4-960e-f0afd4dfecad)
, how should I interpret these sites.

Also, the maximum probability_modified in my results is only 0.35 and mod_ratio is 0.15 (data ERR4706156), which doesn't seem to be the expected result. Do you have any suggestions as to what is causing the low probability_modified and mod_ratio?

Thanks,

LeeLee

**Comment by yuukiiwa** [comment]
Hi LeeLee (tagging you here @lbwfff),

Do you mind sharing the command you used to run `m6anet inference`, please? Also is your sample sequenced with RNA002 or RNA004?

Thanks!

Best wishes,
Yuk Kei

**Comment by lbwfff** [comment]
Hi Yuk, here are the parameters I used:

```
m6anet dataprep --eventalign /scratch/lb4489/project/dRNA/WT1_temp/ALL_eventalign.txt \
        --out_dir WT_1_m6anet \
        --n_processes 120

m6anet inference --input_dir WT_1_m6anet --out_dir WT_1_m6anet_result  --pretrained_model HEK293T_RNA004 --n_processes 120 --num_iterations 1000
```

The data source is from the xpore paper, so it should be RNA002

**Comment by yuukiiwa** [comment]
Hi LeeLee (@lbwfff),

You are using the RNA004 pretrained model, so the following command without specifying using the RNA004 model should work for your RNA002 data (also m6anet inference doesn't require much CPU to run):

```
m6anet inference --input_dir WT_1_m6anet --out_dir WT_1_m6anet_result  --n_processes 7
```

Thanks!

Best wishes,
Yuk Kei
