### ISSUE TITLE
f5c or nanopolish

### ISSUE THREAD

**Issue by JSluo888** [GoekeLab/m6anet#169]
Should we use f5c or nanopolish for indexing and eventalign, if our reads are RNA002?

**Comment by ritianjiang** [comment]
I guess you can use the nanopolish and the older release of m6anet like v2.0.0

**Comment by JSluo888** [comment]
> I guess you can use the nanopolish and the older release of m6anet like v2.0.0

Do you think the current m6anet version would not support RNA002 reads?

**Comment by ritianjiang** [comment]
> > I guess you can use the nanopolish and the older release of m6anet like v2.0.0
> 
> Do you think the current m6anet version would not support RNA002 reads?

No. 😂I ignored that authors have provided both RNA002 model and RNA004 model in 2.1.0

**Comment by yuukiiwa** [comment]
Hi @JSluo888,

Either nanopolish or f5c should work.

Thanks!

Best wishes,
Yuk Kei
