### ISSUE TITLE
Disconnect between site and individual read mod probability RNA004

### ISSUE THREAD

**Issue by esh97** [GoekeLab/m6anet#170]
Hello, 

Thank you for creating this easy to use tool! I've used it in the past for my RNA002 data, and it has worked very well. I just generated some RNA004 data and saw that there are two output files from the inference command. However, the sites of high probability in the site output do not show as high probability in the individual read output. Could you explain why this might be the case? Thanks!

Ethan

**Comment by yuukiiwa** [comment]
Hi Ethan (tagging you here @esh97),

The `probability_modified` from `data.site_proba.csv` assumes that a site is modified if at least one of its reads is modified, so a site can have a high `probability_modified` in `data.site_proba.csv` even if not all `probability_modified` from `data.indiv_proba.csv` are high.

Thanks!

Best wishes,
Yuk Kei
