### ISSUE TITLE
unmodified control library

### ISSUE THREAD

**Issue by baibing7713661** [GoekeLab/m6anet#22]
Hi Christopher,
Thanks for releasing the new method for mapping m6A with direct RNA sequencing. I would like to know if the unmodified library is needed with this method for mapping m6A as my understanding from this paper is that the method is trained so that unmodified library is not needed anymore to map m6A. Since I am going to deliver samples for sequencing, this is important to know. Thanks.

Regards
Bing

**Comment by chrishendra93** [comment]
hi @baibing7713661,

The unmodified library is not needed with this method

Regards

Christopher Hendra
