### ISSUE TITLE
Kmer

### ISSUE THREAD

**Issue by al3xMlt** [GoekeLab/m6anet#24]
What are possible reasons, why a DRACH motif is not processed?

Kind regards

Alex

**Comment by chrishendra93** [comment]
Apology for the late reply,

It's either they do not have enough reads or when aligned with nanopolish, the reference kmer and model kmer are different in nanopolish eventalign

**Comment by al3xMlt** [comment]
Do you know what can cause the problem, that aligning with nanopolish the refernce kmer and the model kmer differs? Is it a basecalling error? And If yes, cant this be associated (if EpiNano is to believed) with a m6A modification? Also the publication of João H. C. Campos et.al observed C > U change in the fourth position of DRACH which affects methylation. This positions would also not be processed right? I am very curious about your expertise and your thoughts about it!
Best 
-alex
