### ISSUE TITLE
Pre-training model provided by m6anet for predict m6a sites

### ISSUE THREAD

**Issue by Derryxu** [GoekeLab/m6anet#34]
Hi,
Thanks for releasing the model for m6anet. The pre-training model provided by m6anet for predicting m6a sites is trained in a single replicate (replicate 2 run 1) of the HCT116 cell line. Is that correct? Looking foward for your review. Thank you very much.

xu

**Comment by chrishendra93** [comment]
Hi @Derryxu , 

It is correct that the m6Anet model is trained on the siingle replicate (replicate 2 run 1) of the HCT116 cell line.

Regards

Christopher Hendra
