### ISSUE TITLE
Few m6a sites detected

### ISSUE THREAD

**Issue by MiphaZ** [GoekeLab/m6anet#35]
Hi,
I downloaded HEK293T-WT data which includes a eventalign result from xPore and it's preparation is as same as that in your article. 
I performed m6anet-dataprep and got this warning:

> /home/yuan/.local/lib/python3.9/site-packages/m6anet/scripts/dataprep.py:142: SettingWithCopyWarning: 
> A value is trying to be set on a copy of a slice from a DataFrame.
> Try using .loc[row_indexer,col_indexer] = value instead
> 
> See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
>   chunk_split['line_length'] = np.array(lines)
> /home/yuan/.local/lib/python3.9/site-packages/m6anet/scripts/dataprep.py:100: PerformanceWarning: indexing past lexsort depth may impact performance.
>   pos_end += eventalign_result.loc[index]['line_length'].sum()

Then I tried m6anet-run_inference and only found 33 m6a sites.
Here is my commands:

> m6anet-dataprep --eventalign eventalign.txt --out_dir m6a --n_processes 20
> m6anet-run_inference --input_dir m6a --out_dir m6a --n_processes 10

 Could you give me some suggestions about this issue? Thank you very much!

**Comment by chrishendra93** [comment]
hi @MiphaZ ,

Can I check with you how do you threshold the m6a sites? Furthermore, can I check how many entries are there in data.readcount file?

**Comment by MiphaZ** [comment]
Thanks for your reply
The data.readcount file includes 150 lines and here is part of it:

> transcript_id,transcript_position,n_reads
> ENST00000210444,347,1
> ENST00000210444,441,1
> ENST00000210444,476,1
> ENST00000210444,695,1
> ENST00000210444,787,1
> ENST00000210444,794,1
> ENST00000210444,815,1
> ENST00000210444,843,1

I don't quite understand the threshold you point out (please forgive my poor english) , but I just used the default setting in 'quick start' and the total number including low probability-modified sites is 33.

**Comment by chrishendra93** [comment]
There should be more than 150 lines if you preprocess the entire dataset. Is this the eventalign result from the full HEK293T datasets?

**Comment by MiphaZ** [comment]
The eventalign file size is 36Mb and the fast5 file size is 16Mb.
I downloaded this from the xpore documentation:
> https://xpore.readthedocs.io/en/latest/quickstart.html

**Comment by MiphaZ** [comment]
Is this demo data just contains a part of HEK293T dataset?

**Comment by chrishendra93** [comment]
Hi YuanMei, this is a demo data, the original HEK293T dataset is hosted
here https://www.ebi.ac.uk/ena/browser/view/PRJEB40872?show=reads

**Comment by kwonej0617** [comment]
Hi @chrishendra93 

Is there a way to remove threshold >=20 reads or modify the threshold?
Thanks!
