### ISSUE TITLE
output the read level modification probability

### ISSUE THREAD

**Issue by guowb9** [GoekeLab/m6anet#47]
Hi,
thanks a lot for developing m6anet!
I have successfully run my data with m6anet. But I have a question, can I output the read level modification probability for specific sites?

Best wishes.

**Comment by chrishendra93** [comment]
hi @guowb9 , yes if you are using m6anet 1.2 you can output the read level modification probability for specific sites using the flag --infer_mod_rate

**Comment by guowb9** [comment]
Great, thanks a lot for your reply!

**Comment by haotianteng** [comment]
Where to find the read level probability? I found there is a data.json file, and every line contains a N-by-9 matrix, how to interpret this matrix? 

Best
