### ISSUE TITLE
m6anet publication

### ISSUE THREAD

**Issue by kwonej0617** [GoekeLab/m6anet#48]
Hi developer, 

I only found m6anet paper in biorxiv. I was just wondering if m6anet has been published in a peer-reviewed journal. 

Thank you!

**Comment by chrishendra93** [comment]
hi @kwonej0617, sorry for the late reply. m6Anet is currently under review and we hope that you will see it published in the coming months, do follow us on twitter at @goekelab and @chrishendra_93 for the update
