### ISSUE TITLE
m6anet-run_inference error

### ISSUE THREAD

**Issue by rezarahman12** [GoekeLab/m6anet#53]
Dear m6Anet
Thank you and congratulations on getting m6Anet published in Nat. methods.
I tried m6anet-run_inference on single replicate and it worked well. But, when I have given three replicates of a sample (wildtype), a error came, similar to #38 . 
The below is my script-

module load m6anet

m6anet-run_inference --input_dir /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/m6anet/dataprep/wt-rep1 \
                                /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/m6anet/dataprep/wt-rep2 \
                               /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/m6anet/dataprep/wt-rep3 \

                     --out_dir /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/m6anet/m6a_infer \
                     --infer_mod_rate \
                     --n_processes 1 

The screenshot of the error is given below-
![image](https://user-images.githubusercontent.com/110575883/201500127-b95d3a58-0b21-40ab-a676-f466d44b8d74.png)

I ran the job in HPC cluster server using a PBS script, and the m6anet was loaded through module load m6anet. I do not know how to add your suggestion in the issue #38 "Inserting the torch.multiprocessing.set_sharing_strategy('file_system') line in the /home/stakatis/miniconda3/envs/m6anet/lib/python3.9/site-packages/m6anet/scripts/run_inference.py ".  

Could you please advise any solution to this problem? 
Kind regards
Reza

**Comment by chrishendra93** [comment]
hi @rezarahman12 , recently I found out that setting --n_processes 0 seems to solve this problem for me.https://pytorch.org/docs/stable/data.html suggests that setting num_workers to 0, in our case this is n_processes, will disable multiprocesses which might help with our problem over here. Let me know if this works for you

**Comment by rezarahman12** [comment]
Hi Christopher,
Thank you so much for your quick response and time. It worked for me. Thank you.

I have another question regarding converting the transcript ID and its position obtained through m6Anet into genes and genomic position. So, I'm creating another new issue on that.

Thanks a lot.
Best regards
Reza
