### ISSUE TITLE
converting transcripts and transcriptomic position obtained through m6Anet into genomic coordinates 

### ISSUE THREAD

**Issue by rezarahman12** [GoekeLab/m6anet#54]
Dear Christopher,

I have a question on converting the transcript ID and its position obtained through m6Anet into genes and genomic position. 

Could you please advise on how to change the transcript id and transcript position into gene and genomic position, which you have reported in your m6Anet paper (supplementary table1)?

I appreciate your time and help.

Thanks a lot.
Best regards
Reza

**Comment by chrishendra93** [comment]
Hi @rezarahman12 

I used the following function (adapted from xPore dataprep.py)

```
def t2g(tx_id, fasta_dict, gtf_dict):
    t2g_dict = {}
    tx_seq = fasta_dict[tx_id]
    tx_contig = gtf_dict[tx_id]['chr']
    g_id = gtf_dict[tx_id]['g_id']
    if tx_seq is None:
        return [], []

    for exon_num in range(len(gtf_dict[tx_id]['exon'])):
        g_interval = gtf_dict[tx_id]['exon'][exon_num]
        tx_interval = gtf_dict[tx_id]['tx_exon'][exon_num]
        for g_pos in range(g_interval[0], g_interval[1] + 1): # Exclude the rims of exons.
            dis_from_start = g_pos - g_interval[0]
            if gtf_dict[tx_id]['strand'] == "+":
                tx_pos = tx_interval[0] + dis_from_start
            elif gtf_dict[tx_id]['strand'] == "-":
                tx_pos = tx_interval[1] - dis_from_start
            if (g_interval[0] <= g_pos < g_interval[0]+2) or (g_interval[1]-2 < g_pos <= g_interval[1]): 
                kmer = 'XXXXX'
            else:
                kmer = tx_seq[tx_pos-2:tx_pos+3]
            t2g_dict[tx_pos] = (tx_contig, g_id, g_pos) # tx.contig is chromosome.
    return t2g_dict

def readFasta(transcript_fasta_paths_or_urls):
    fasta=open(transcript_fasta_paths_or_urls,"r")
    entries=""
    for ln in fasta:
        entries+=ln
    entries=entries.split(">")
    dict={}
    for entry in entries:
        entry=entry.split("\n")

        if len(entry[0].split()) > 0:
            id=entry[0].split()[0].split(".")[0]
            seq="".join(entry[1:])
            dict[id]=seq
    return dict

def readGTF(gtf_path_or_url):
    gtf=open(gtf_path_or_url,"r")
    dict={}
    for ln in gtf:
        if not ln.startswith("#"):
            ln=ln.strip("\n").split("\t")
            if ln[2] == "transcript" or ln[2] in ("exon", "start_codon", "stop_codon", "CDS", 
                                                  "three_prime_utr", "five_prime_utr"):
                chr,type,start,end=ln[0],ln[2],int(ln[3]),int(ln[4])
                attrList=ln[-1].split(";")
                attrDict={}
                for k in attrList:
                    p=k.strip().split(" ")
                    if len(p) == 2:
                        attrDict[p[0]]=p[1].strip('\"')
                tx_id = attrDict["transcript_id"]
                g_id = attrDict["gene_id"]
                if tx_id not in dict:
                    dict[tx_id]={'chr':chr,'g_id':g_id,'strand':ln[6]}
                    if type not in dict[tx_id]:
                        if type == "transcript":
                            dict[tx_id][type]=(start,end)
                else:
                    if type == 'CDS':
                        info = (start, end, int(attrDict['exon_number']))
                    else:
                        info = (start, end)
                    if type not in dict[tx_id]:
                        dict[tx_id][type]=[info]
                    else:
                        dict[tx_id][type].append(info)
                        

                        
    #convert genomic positions to tx positions
    for id in dict:
        tx_pos,tx_start=[],0
        for pair in dict[id]["exon"]:
            tx_end=pair[1]-pair[0]+tx_start
            tx_pos.append((tx_start,tx_end))
            tx_start=tx_end+1
        dict[id]['tx_exon']=tx_pos
    return dict
```
There are three functions there that are needed to map transcript id to genomic position. First you need to supply the fasta file and the gtf file to two functions in there:
```
fasta_dict = readFasta(fasta_path)
gtf_dict = readGTF(gtf_path)
t2g_dict = {tx: t2g(tx, fasta_dict, gtf_dict) for tx in all_transcripts
```

Here t2g_dict contains the dictionary mapping transcript position to the genomic position for all transcripts. For my use case, I assumed ensemble annotation so you might need to adapt these functions for other kind of annotations. I think these functions are implemented more generally in xPore dataprep.py

**Comment by rezarahman12** [comment]
Thanks, Christopher for your quick response. I'll give it a shot and will update you on this.

**Comment by rezarahman12** [comment]
Dear Christopher,
I made m6anet_t2g.py file that contains below script:

def t2g(tx_id, fasta_dict, gtf_dict):
    t2g_dict = {}
    tx_seq = fasta_dict[tx_id]
    tx_contig = gtf_dict[tx_id]['chr']
    g_id = gtf_dict[tx_id]['g_id']
    if tx_seq is None:
        return [], []

    for exon_num in range(len(gtf_dict[tx_id]['exon'])):
        g_interval = gtf_dict[tx_id]['exon'][exon_num]
        tx_interval = gtf_dict[tx_id]['tx_exon'][exon_num]
        for g_pos in range(g_interval[0], g_interval[1] + 1): # Exclude the rims of exons.
            dis_from_start = g_pos - g_interval[0]
            if gtf_dict[tx_id]['strand'] == "+":
                tx_pos = tx_interval[0] + dis_from_start
            elif gtf_dict[tx_id]['strand'] == "-":
                tx_pos = tx_interval[1] - dis_from_start
            if (g_interval[0] <= g_pos < g_interval[0]+2) or (g_interval[1]-2 < g_pos <= g_interval[1]): 
                kmer = 'XXXXX'
            else:
                kmer = tx_seq[tx_pos-2:tx_pos+3]
            t2g_dict[tx_pos] = (tx_contig, g_id, g_pos) # tx.contig is chromosome.
    return t2g_dict

def readFasta(/scratch/project_mnt/S0077/xPore/Homo_sapiens.GRCh38.cdna.all.fa):
    fasta=open(/scratch/project_mnt/S0077/xPore/Homo_sapiens.GRCh38.cdna.all.fa,"r")
    entries=""
    for ln in fasta:
        entries+=ln
    entries=entries.split(">")
    dict={}
    for entry in entries:
        entry=entry.split("\n")

        if len(entry[0].split()) > 0:
            id=entry[0].split()[0].split(".")[0]
            seq="".join(entry[1:])
            dict[id]=seq
    return dict

def readGTF(/scratch/project_mnt/S0077/xPore/Homo_sapiens.GRCh38.91.gtf):
    gtf=open(/scratch/project_mnt/S0077/xPore/Homo_sapiens.GRCh38.91.gtf,"r")
    dict={}
    for ln in gtf:
        if not ln.startswith("#"):
            ln=ln.strip("\n").split("\t")
            if ln[2] == "transcript" or ln[2] in ("exon", "start_codon", "stop_codon", "CDS", 
                                                  "three_prime_utr", "five_prime_utr"):
                chr,type,start,end=ln[0],ln[2],int(ln[3]),int(ln[4])
                attrList=ln[-1].split(";")
                attrDict={}
                for k in attrList:
                    p=k.strip().split(" ")
                    if len(p) == 2:
                        attrDict[p[0]]=p[1].strip('\"')
                tx_id = attrDict["transcript_id"]
                g_id = attrDict["gene_id"]
                if tx_id not in dict:
                    dict[tx_id]={'chr':chr,'g_id':g_id,'strand':ln[6]}
                    if type not in dict[tx_id]:
                        if type == "transcript":
                            dict[tx_id][type]=(start,end)
                else:
                    if type == 'CDS':
                        info = (start, end, int(attrDict['exon_number']))
                    else:
                        info = (start, end)
                    if type not in dict[tx_id]:
                        dict[tx_id][type]=[info]
                    else:
                        dict[tx_id][type].append(info)
                        
                        
    #convert genomic positions to tx positions
    for id in dict:
        tx_pos,tx_start=[],0
        for pair in dict[id]["exon"]:
            tx_end=pair[1]-pair[0]+tx_start
            tx_pos.append((tx_start,tx_end))
            tx_start=tx_end+1
        dict[id]['tx_exon']=tx_pos
    return dict

fasta_dict = readFasta(/scratch/project_mnt/S0077/xPore/Homo_sapiens.GRCh38.cdna.all.fa)
gtf_dict = readGTF(/scratch/project_mnt/S0077/xPore/Homo_sapiens.GRCh38.91.gtf)
t2g_dict = {tx: t2g(tx, fasta_dict, gtf_dict) for tx in all_transcripts


#then I prepared a PBS script to run the above code, which is given below:

cd $PBS_O_WORKDIR

python m6anet_t2g.py

#however, I'm getting below error-
###############################################################################
  File "m6anet_t2g.py", line 25
    def readFasta("/scratch/project_mnt/S0077/xPore/Homo_sapiens.GRCh38.cdna.all.fa"):
                                                                                   ^
SyntaxError: invalid syntax
# could you please help me to get rid of this error?

Thank you so much for your time and help.

Kind regards
Reza

**Comment by chrishendra93** [comment]
ah yeah that all_transcripts variable there should be a list of all transcripts that you want to map from your dataset.

**Comment by rezarahman12** [comment]
Thanks for much Chris for your quick reply.
I'm sorry that I'm not good at python coding. I tried to create the object for all_transcript but I'm getting an error. I have uploaded the m6anet_t2g.py, the error file, and the list of transcripts that I obtained through m6anet in google drive for your kind consideration. I'll be very grateful if you kindly check the script and suggest the required changes. The fasta and gtf file I'm using is from Ensemble.
Google drive link for script and file:
https://drive.google.com/drive/folders/11FlbKV7Pd_dI9BCm0XdGQK0lX8CvCnBr?usp=share_link
I do highly appreciate your time and help.
Kind regards,
Reza

**Comment by chrishendra93** [comment]
hi @rezarahman12 , sorry for the late reply

I have checked your error file and it seems that your all_transcripts is empty, and it is caused by your function read_all_transcripts which do not return anything. I have included the modification below

     def readalltranscript(intranscript):
        all_transcripts = []
        i = 0
        with open(intranscript,"r") as f:
            for line in f:
                if i == 0:
                    i+=1
                    continue
                 else:
                    all_transcripts.append(line.strip("\n"))
      return all_transcripts

**Comment by rezarahman12** [comment]
Hi Christopher (@chrishendra93),
Thank you so much for your time and help. 
I've tried the modified script you suggested. I'm having a minor error "IndentationError". I have uploaded the updated "m6anet_t2g.py" script and error file in the below google drive link. Could you please have a look at your convenient time?
I'm sorry to bother you again.
Google drive link:
https://drive.google.com/drive/folders/11FlbKV7Pd_dI9BCm0XdGQK0lX8CvCnBr?usp=share_link
Thank you again.
Kind regards
Reza

**Comment by chrishendra93** [comment]
hi @rezarahman12 , the error just means that the function was not indented properly since python expects indentation. I tried to correct the indentation on my code editor, maybe try this one

    def readalltranscript(intranscript):
        all_transcripts = []
        i = 0
        with open(intranscript,"r") as f:
            for line in f:
                if i == 0: # Skip the first line
                    i+=1
                    continue
                else:
                    all_transcripts.append(line.strip("\n"))
        return all_transcripts

**Comment by rezarahman12** [comment]
Dear Christopher,
Thank you so much for your time and help. I'm now getting the same error again as previously. I've updated the script according to your advice. Would you mind opening see the problem in the script? The updated script in the google drive, which I shared in the past message.
I'm really sorry for bothering you.
I appreciate your time and help.
Best regards
Reza

**Comment by chrishendra93** [comment]
hi @rezarahman12, the problem with your script is that it was not indented properly, which is required by the Python language. I have modified your script by correcting the indentation, nevertheless, you will still need to map the coordinates. The t2g_dict object gives you a mapping for each transcript id and transcript position which you will need to map the m6Anet coordinates

**Comment by rezarahman12** [comment]
Dear Christopher (@chrishendra93),
Thank you so much for your time and help. Yes, there is no _"ndentation_ Error" now with your modified script. However, I'm getting another error "KeyError". 
Error message pasted below:
Traceback (most recent call last):
  File "m6anet_t2g.py", line 102, in <module>
    t2g_dict = {tx: t2g(tx, fasta_dict, gtf_dict) for tx in all_transcripts}
  File "m6anet_t2g.py", line 102, in <dictcomp>
    t2g_dict = {tx: t2g(tx, fasta_dict, gtf_dict) for tx in all_transcripts}
  File "m6anet_t2g.py", line 5, in t2g
    tx_seq = fasta_dict[tx_id]
KeyError: 'ENST00000533683.6'
Could you please suggest further to avoid this error?
Best regards
Reza

**Comment by chrishendra93** [comment]
Hi @rezarahman12 , my suspicion is that the key inside the fastadict dictionary does not have the dot in the transcript name. You can just strip the dot from tx_id, for example, instead of fasta_dict[tx_id], you can do fasta_dict[tx_id.split(".")[0]]

**Comment by SamErnRoss** [comment]
> Thanks for much Christopher (@chrishendra93) for your quick reply. I'm sorry that I'm not good at python coding. I tried to create the object for all_transcript but I'm getting an error. I have uploaded the m6anet_t2g.py, the error file, and the list of transcripts that I obtained through m6anet in google drive for your kind consideration. I'll be very grateful if you kindly check the script and suggest the required changes. The fasta and gtf file I'm using is from Ensemble. Google drive link for script and file: https://drive.google.com/drive/folders/11FlbKV7Pd_dI9BCm0XdGQK0lX8CvCnBr?usp=share_link I do highly appreciate your time and help. Kind regards, Reza



Hello @rezarahman12 ,

here is a rough way to convert the output of m6anet to genomic coordinates using bash and bedtools if you are having problems with python. I haven't extensively tested it though and am not affiliated with this tool so use with caution.

`#get all exons from a GTF file and print ENS/gene, length, chr, start, end, strand
awk '$3=="exon"' file.gtf | awk '{print $14,$5-$4,$1,$4,$5,$7}' | sed 's/"//g; s/;//g; s/ /\t/g' > transcript_coord_tmp

#print ENS, exon_start (relative to transcript), exon_end (relative to transcript),chr,exon_start(relative to genome), exon_end (relative to genome), and filter out 1bp exons.
awk '{print $1, $2, sum[$1]+0, $3, $4, $5, $6; sum[$1] += $2}' transcript_coord_tmp | awk '{OFS="\t"}{print $1,$3+1,$3+$2,$4,$5,$6,$7}' | awk '$3>$2' > transcript_coord

#convert m6a output into bed relative to ENS/gene
zcat data.result.csv.gz | sed 's/,/\t/g; s/\./\t/' | awk '{OFS="\t"}{print $1,$3,$3+1,$7}' | sed '1d' > data_results

#intersect transcript_coord file with data_results and print both entries
bedtools intersect -wo -a transcript_coord -b data_results > data_coordinates

#convert to genome relative bed, here i also filter out alt chromosomes and contigs.
awk '{OFS="\t"}{if ($7=="+") print "chr"$4,$5+($9-$2),$5+($10-$2),$11; else print "chr"$4,$6-($10-$2),$6-($9-$2),$11}' data_coordinates | awk '$2<$3' | sort -k1,1 -k2,2n | grep -v "G\|K\|K\|M" > data_m6a.bg

#merge entries that overlap (as transcript isoforms will have different m6a calls at the same genomic position), this is optional but required for bigwigs
bedtools merge -i data_m6a.bg -c 4 -o mean > data_m6a_merge.bg

#make bigwigs
bedGraphToBigWig data_m6a_merge.bg hg38.chrom data_m6a.bw
`

**Comment by SamErnRoss** [comment]
Hello @rezarahman12 ,

here is a rough way to convert the output of m6anet to genomic coordinates using bash and bedtools if you are having problems with python. I haven't extensively tested it though and am not affiliated with this tool so use with caution.

```#get all exons from a GTF file and print ENS/gene, length, chr, start, end, strand
awk '$3=="exon"' file.gtf | awk '{print $14,$5-$4,$1,$4,$5,$7}' | sed 's/"//g; s/;//g; s/ /\t/g' > transcript_coord_tmp

#print ENS, exon_start (relative to transcript), exon_end (relative to transcript),chr,exon_start(relative to genome), exon_end (relative to genome), and filter out 1bp exons.
awk '{print $1, $2, sum[$1]+0, $3, $4, $5, $6; sum[$1] += $2}' transcript_coord_tmp | awk '{OFS="\t"}{print $1,$3+1,$3+$2,$4,$5,$6,$7}' | awk '$3>$2' > transcript_coord

#convert m6a output into bed relative to ENS/gene
zcat data.result.csv.gz | sed 's/,/\t/g; s/./\t/' | awk '{OFS="\t"}{print $1,$3,$3+1,$7}' | sed '1d' > data_results

#intersect transcript_coord file with data_results and print both entries
bedtools intersect -wo -a transcript_coord -b data_results > data_coordinates

#convert to genome relative bed, here i also filter out alt chromosomes and contigs.
awk '{OFS="\t"}{if ($7=="+") print "chr"$4,$5+($9-$2),$5+($10-$2),$11; else print "chr"$4,$6-($10-$2),$6-($9-$2),$11}' data_coordinates | awk '$2<$3' | sort -k1,1 -k2,2n | grep -v "G|K|K|M" > data_m6a.bg

#merge entries that overlap (as transcript isoforms will have different m6a calls at the same genomic position), this is optional but required for bigwigs
bedtools merge -i data_m6a.bg -c 4 -o mean > data_m6a_merge.bg

#make bigwigs
bedGraphToBigWig data_m6a_merge.bg hg38.chrom data_m6a.bw
```

**Comment by SamErnRoss** [comment]
Hi @rezarahman12 ,
Here is a rough way of converting the m6a output to genomic coordinates, using the GTF file, bash and bedtools if you are still having problems with the python script. However, i haven't extensively tested and tweaked this code, nor am not affiliated with this tool, so i would use with caution.

```
#get all exons and print ENST,length,chr,start,end,strand
awk '$3=="exon"' file.gtf | awk '{print $14,$5-$4,$1,$4,$5,$7}' | sed 's/"//g; s/;//g; s/ /\t/g' > transcript_coord_tmp

#print ENST, exon_start (relative to transcript), exon_end (relative to transcript),chr,exon_start(relative to genome), exon_end (relative to genome), and filter out 1bp exons.
awk '{print $1, $2, sum[$1]+0, $3, $4, $5, $6; sum[$1] += $2}' transcript_coord_tmp | awk '{OFS="\t"}{print $1,$3+1,$3+$2,$4,$5,$6,$7}' | awk '$3>$2' > transcript_coord

#convert m6a output into bed relative to ENST
zcat data.result.csv.gz | sed 's/,/\t/g; s/\./\t/' | awk '{OFS="\t"}{print $1,$3,$3+1,$7}' | sed '1d' > data_results

#intersect transcript_coord file with data_results and print both entries
bedtools intersect -wo -a transcript_coord -b data_results > data_coordinates

#convert to genome relative bed, here i also filter out alt chromosomes and contigs.
awk '{OFS="\t"}{if ($7=="+") print "chr"$4,$5+($9-$2),$5+($10-$2),$11; else print "chr"$4,$6-($10-$2),$6-($9-$2),$11}' data_coordinates | awk '$2<$3' | sort -k1,1 -k2,2n | grep -v "G\|K\|K\|M" > data_m6a.bg

#merge entries that overlap (as transcript isoforms will have different m6a calls at the same genomic position), this is optional but required for bigwigs.
bedtools merge -i data_m6a.bg -c 4 -o mean > data_m6a_merge.bg

#make bigwigs
bedGraphToBigWig data_m6a_merge.bg hg38.chrom data_m6a.bw
```

**Comment by acarmas1** [comment]
Hello,

I'm trying to also use this script to identify the genomic position of my transcripts. I run this script:

......
#!/usr/bin/env python

def t2g(tx_id, fasta_dict, gtf_dict):
    t2g_dict = {}
    tx_seq = fasta_dict[tx_id.split(".")[0]]
    tx_contig = gtf_dict[tx_id]['chr']
    g_id = gtf_dict[tx_id]['g_id']
    if tx_seq is None:
        return [], []

    for exon_num in range(len(gtf_dict[tx_id]['exon'])):
        g_interval = gtf_dict[tx_id]['exon'][exon_num]
        tx_interval = gtf_dict[tx_id]['tx_exon'][exon_num]
        for g_pos in range(g_interval[0], g_interval[1] + 1): # Exclude the rims of exons.
            dis_from_start = g_pos - g_interval[0]
            if gtf_dict[tx_id]['strand'] == "+":
                tx_pos = tx_interval[0] + dis_from_start
            elif gtf_dict[tx_id]['strand'] == "-":
                tx_pos = tx_interval[1] - dis_from_start
            if (g_interval[0] <= g_pos < g_interval[0]+2) or (g_interval[1]-2 < g_pos <= g_interval[1]): 
                kmer = 'XXXXX'
            else:
                kmer = tx_seq[tx_pos-2:tx_pos+3]
            t2g_dict[tx_pos] = (tx_contig, g_id, g_pos) # tx.contig is chromosome.
    return t2g_dict

def readFasta(infasta):
    fasta=open(infasta,"r")
    entries=""
    for ln in fasta:
        entries+=ln
    entries=entries.split(">")
    dict={}
    for entry in entries:
        entry=entry.split("\n")

        if len(entry[0].split()) > 0:
            id=entry[0].split()[0].split(".")[0]
            seq="".join(entry[1:])
            dict[id]=seq
    return dict

def readGTF(ingtf):
    gtf=open(ingtf,"r")
    dict={}
    for ln in gtf:
        if not ln.startswith("#"):
            ln=ln.strip("\n").split("\t")
            if ln[2] == "transcript" or ln[2] in ("exon", "start_codon", "stop_codon", "CDS", 
                                                  "three_prime_utr", "five_prime_utr"):
                chr,type,start,end=ln[0],ln[2],int(ln[3]),int(ln[4])
                attrList=ln[-1].split(";")
                attrDict={}
                for k in attrList:
                    p=k.strip().split(" ")
                    if len(p) == 2:
                        attrDict[p[0]]=p[1].strip('\"')
                tx_id = attrDict["transcript_id"]
                g_id = attrDict["gene_id"]
                if tx_id not in dict:
                    dict[tx_id]={'chr':chr,'g_id':g_id,'strand':ln[6]}
                    if type not in dict[tx_id]:
                        if type == "transcript":
                            dict[tx_id][type]=(start,end)
                else:
                    if type == 'CDS':
                        info = (start, end, int(attrDict['exon_number']))
                    else:
                        info = (start, end)
                    if type not in dict[tx_id]:
                        dict[tx_id][type]=[info]
                    else:
                        dict[tx_id][type].append(info)
                        
                      
    #convert genomic positions to tx positions
    for id in dict:
        tx_pos,tx_start=[],0
        for pair in dict[id]["exon"]:
            tx_end=pair[1]-pair[0]+tx_start
            tx_pos.append((tx_start,tx_end))
            tx_start=tx_end+1
        dict[id]['tx_exon']=tx_pos
    return dict

def readalltranscript(intranscript):
    all_transcripts = []
    i = 0
    with open(intranscript,"r") as f:
        for line in f:
            if i == 0: # Skip the first line
                i+=1
                continue
            else:
                all_transcripts.append(line.strip("\n"))
    return all_transcripts  

fasta_dict = readFasta("/projects/dsn001/camila/m6A/genomes/ApisMellifera_RNA.fasta")
gtf_dict = readGTF("/projects/dsn001/camila/m6A/genomes/GCF_003254395.2_Amel_HAv3.1_genomic.gtf")
all_transcripts = readalltranscript("/projects/dsn001/camila/m6A/m6anet_analysis/pooled_rep/Rfiltered_data/trans2.txt")
t2g_dict = {tx: t2g(tx, fasta_dict, gtf_dict) for tx in all_transcripts

.....

But at the end I'm getting this error:

![image](https://user-images.githubusercontent.com/33578163/216237472-3241ee2c-1f12-4767-badd-894c5936467f.png)

Please if you can help me to troubleshoot this issue, I'll appreciate it. 

Thank you
