### ISSUE TITLE
how to train model on all middle A 5-mer motif

### ISSUE THREAD

**Issue by JeremyQuo** [GoekeLab/m6anet#55]

**Comment by JeremyQuo** [comment]
I wanna extract all middle A features and train a new model . Is there any more pipeline  ?

**Comment by chrishendra93** [comment]
hi @JeremyQuo , currently we do not support any feature to train a new model with different 5-mer motifs. Regardless, you can adapt our code to do this by modifying the ALL_KMERS constant variable in m6anet/constants.py
