### ISSUE TITLE
Understanding embedding layer dimensions

### ISSUE THREAD

**Issue by ChaseWLW** [GoekeLab/m6anet#56]
Dear authors,

Congrats on the publication! 

I am a bit confused over the 66-dimension kmer-embedding layer. How do we go from DRACH motifs to an encoding of 66 dimensions? Thanks and keep up the good work!

**Comment by hengjwj** [comment]
Hi Christopher, I'm still unclear about how to get 66 and hope you could help clarify. From what I understand, DRACH comprises 18 unique 5-mer motifs (3x2x1x1x3). Wouldn't adding DRACH's flanking +/- 1 position then make the total = (4x18x4) = 288?
