### ISSUE TITLE
m6anet -train on demo data : indexer out of bound error

### ISSUE THREAD

**Issue by JiayiLi21** [GoekeLab/m6anet#57]
Hi developers,
After steps of installation, dataprep, run_inference based on the documentation and your demo data , there is an error in the training session which indicates a common index out of bound issue. I have checked relevant scripts and run the procedure several times ,but cannot figure out what is wrong.Could you please help to solve this problem? 
Many thanks
![截屏2022-11-19 20 20 55](https://user-images.githubusercontent.com/90132238/202852992-d44c70dd-5ef6-442f-8733-d001fde20351.png)

**Comment by chrishendra93** [comment]
hi @JiayiLi21 , thanks for reporting this issue. I am a bit occupied at the moment but I will look into this, and get back to you hopefully in the next day or two. 

Regards

Christopher Hendra

**Comment by chrishendra93** [comment]
hi @JiayiLi21 , I found the error from my end. Sorry it seems that I supply the data.readcount.labelled in the wrong format, if you look at data.index, all transcripts have "." in their names but not in data.readcount.labelled (for example, ENST00000361055 and ENST00000361055.8). I have pushed an updated data.readcount.labelled to the demo folder, check it out and let me know if it works!

**Comment by JiayiLi21** [comment]
Thank you@chrishendra93 It works!
