### ISSUE TITLE
The kit used for the cell line

### ISSUE THREAD

**Issue by LuckyMLucy** [GoekeLab/m6anet#60]
Dear developer，

    Could you please tell me the kit used for the cell line?
    Thanks you~

**Comment by chrishendra93** [comment]
hi @LuckyMLucy , the cell lines we used came from other publications:

- HEK293T cell lines: https://www.nature.com/articles/s41587-021-00949-w
- HCT116 cell lines: https://www.biorxiv.org/content/10.1101/2021.04.21.440736v1.full.pdf
- Arabidopsis mutants: https://elifesciences.org/articles/49658#data
- curlcake synthetic sequences: https://www.nature.com/articles/s41467-019-11713-9

you can check out these publications for the details

Christopher

**Comment by LuckyMLucy** [comment]
Ok，thanks for your reply~ @chrishendra93
