### ISSUE TITLE
cannot convert float NaN to integer

### ISSUE THREAD

**Issue by William-chen777** [GoekeLab/m6anet#63]
Dear developer:
  the first i run the command as:
`nanopolish eventalign --reads *.fastq --bam *.sorted.bam --genome *.transcript.fa --scale-events --signal-index --summary sequencing_summary.txt --threads 20 > TAIR.eventalign.txt`

And I have the result like this:
`AT5G67640.1     730     CAAAT   1075535 t       755     73.10   1.352   0.00266 NNNNN   0.00    0.00    inf     53612   53620
AT5G67640.1     730     CAAAT   1075535 t       756     72.66   1.133   0.00465 NNNNN   0.00    0.00    inf     53598   53612
AT5G67640.1     733     ATTAT   1075535 t       757     84.22   1.281   0.00631 ATTAT   85.44   2.46    -0.45   53579   53598
AT5G67640.1     733     ATTAT   1075535 t       758     86.30   1.625   0.00398 ATTAT   85.44   2.46    0.32    53567   53579
AT5G67640.1     733     ATTAT   1075535 t       759     83.94   2.413   0.00764 ATTAT   85.44   2.46    -0.55   53544   53567
AT5G67640.1     733     ATTAT   1075535 t       760     85.55   2.191   0.00199 ATTAT   85.44   2.46    0.04    53538   53544
AT5G67640.1     733     ATTAT   1075535 t       761     88.30   1.888   0.00332 ATTAT   85.44   2.46    1.05    53528   53538
AT5G67640.1     733     ATTAT   1075535 t       762     104.53  3.602   0.00896 NNNNN   0.00    0.00    inf     53501   53528
AT5G67640.1     733     ATTAT   1075535 t       763     111.75  3.878   0.01129 NNNNN   0.00    0.00    inf     53467   53501
AT5G67640.1     733     ATTAT   1075535 t       764     120.04  2.636   0.00299 ATTAT   85.44   2.46    12.66   53458   53467
`
And then when I run the command like "m6anet-dataprep --eventalign TAIR.eventalign.txt --out_dir ./output --n_processes 20", I have the problem like this:
`Process Consumer-9:
Traceback (most recent call last):
  File "/home/wwkong/miniconda3/envs/m6anet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/wwkong/miniconda3/envs/m6anet/lib/python3.8/site-packages/m6anet-1.1.1-py3.8.egg/m6anet/scripts/helper.py", line 113, in run
    result = self.task_function(*next_task_args,self.locks)
  File "/home/wwkong/miniconda3/envs/m6anet/lib/python3.8/site-packages/m6anet-1.1.1-py3.8.egg/m6anet/scripts/dataprep.py", line 103, in index
    f_index.write('%s,%d,%d,%d\n' %(transcript_id,read_index,pos_start,pos_end))
ValueError: cannot convert float NaN to integer`

Can you help me? Best wishes.

**Comment by chrishendra93** [comment]
hi @William-chen777, sorry for the delay in my reply as I was not available last week. Can you provide me the first five rows of your nanopolish eventalign along with the column names just so that I can check the formatting? Currently the output that you provided me omits the column names. The error is because there is NaN output in your eventalign row which should not be the case unless the input format is wrong

**Comment by William-chen777** [comment]
> 

dear developer, thanks for your replying, this is my nanopolish eventalign result:
![image](https://user-images.githubusercontent.com/51122862/207519699-1b92c884-e6c5-485d-9336-814d700cad62.png)

**Comment by William-chen777** [comment]
> 

okey, Thank you ,I'll have a try. Best wishes!
