### ISSUE TITLE
Where to find read-level probability?

### ISSUE THREAD

**Issue by haotianteng** [GoekeLab/m6anet#67]
Hi according to this thread #47
I turn on the  --infer_mod_rate flag, and it now gives a mod_ratio entry which gives the ratio, but I still can't find the read level probability, I find there is a data.json file contains N-by-9 matrix, is the read level probability in this matrix? And if so how should I interpret it?

Best,
Teng

**Comment by chrishendra93** [comment]
hi @haotianteng , currently the --infer_mod_rate flag only gives you the modification percentage of any given site. We have not released the version with the read level probability but if you are interested to try, you can run the dev branch (you don't have to include the --infer_mod_rate flag anymore in this version)

Regards

Christopher Hendra
