### ISSUE TITLE
How can I get the m6a sites data please?

### ISSUE THREAD

**Issue by LuckyMLucy** [GoekeLab/m6anet#70]
Dear developers, sorry to bother you. I have some questions about m6anet.
I was recently doing an analysis on m6a and want to get M6a site modification data for different cell lines (K562, MCF7, HepG2, HCT116, A549), and you mentioned in 《Detection of m6A from direct RNA sequencing using a multiple instance learning framework》, I want to know how can I get the “data.readcount.labeledl” data as provided in the demo folder in your GitHub project?

Looking forward to your reply.
Best Regards!

**Comment by chrishendra93** [comment]
hi @LuckyMLucy sorry for the delay, I was on leave. If you go to the code ocean link as provided in the published article, under the data folder, you can find hct116_data.readcount and hek293_data.readcount. These two contain the modification status that you need
