### ISSUE TITLE
m6anet-run_inference, IndexError: single positional indexer is out-of-bounds

### ISSUE THREAD

**Issue by huawen-poppy** [GoekeLab/m6anet#74]
Dear developers,

Thanks for the nice tool! I tried to run the m6anet-run_inference, but there is an error saying that IndexError: single positional indexer is out-of-bounds. Could you please help me to solve this problem?

I used below code to run:
> m6anet-run_inference --input_dir ./apo/dataprep  --out_dir ./apo/inference --infer_mod_rate --n_processes 4

Please let me know if you need anything from my side. 
Thank you in advance for your help!

Best,
Huawen

**Comment by chrishendra93** [comment]
hi @huawen-poppy, can you show me the first few lines of your eventalign.txt and data.info? I am assuming you're using the latest version of m6anet?

**Comment by huawen-poppy** [comment]
Thank you for getting back to me. Yes, I am using v1.1.1 m6anet. The header of the eventalign.txt looks like below:
![image](https://user-images.githubusercontent.com/70507602/215414994-02faa772-2b81-4d9c-bf7e-a0f472d5fda8.png)

I don't have a file named data.info. Could you please tell me where I can find it?

**Comment by chrishendra93** [comment]
hi @huawen-poppy , sorry I meant data.readcount and data.index

**Comment by huawen-poppy** [comment]
Hello @chrishendra93, thank you for your reply. Below are the first few lines for the data.readcount:
![image](https://user-images.githubusercontent.com/70507602/215998371-82d896c7-0b17-4691-9711-12ee8a875b19.png)

For the data.index file, it looks like:
![image](https://user-images.githubusercontent.com/70507602/215998566-5d2276d4-f8da-4906-a0b6-824bc0a11ebd.png)

**Comment by huawen-poppy** [comment]
Unfortunately, the maximum number of n_reads is 3 in data.readcount

**Comment by chrishendra93** [comment]
hi @huawen-poppy, I think you encountered the error because m6anet cannot find any positions to make inferences from. Currently m6Anet requires at least 20 reads from each position in order to make prediction

**Comment by huawen-poppy** [comment]
Ok, I see. I got this error by directly using all the original fast5 files. I tried to use the pass-quality fast5 files classified by Minknow tool to rerun the analysis. I can successfully run the process. It seems like using all original data directly would cover the signal.
