### ISSUE TITLE
Question regarding supplementary 6 table

### ISSUE THREAD

**Issue by kwonej0617** [GoekeLab/m6anet#93]
Hi, @chrishendra93!

I was just wondering which replicates (among rep1,2,3) of HEK293T WT and KO  you used to generate your supplementary table 6. Also, did you use any filtering before or after running m6anet to get supplementary table 6 result, for example, minimum coverage, and short-length reads?
I really appreciate your help!

**Comment by chrishendra93** [comment]
hi @kwonej0617 , are you talking about supplementary table 2? We used all three replicates for both WT and KO to generate the supplementary table, using the pooling option of xPore so that we can get as many positions as possible. 

Supplementary table 6 is m6Anet prediction on both WT and KO cell lines. For that, we used rep1 if I recall correctly, and a minimum coverage of 20 reads per site

**Comment by kwonej0617** [comment]
Hi, @chrishendra93
I really appreciate your response. Is the filtering for the minimum coverage of 20 reads per site already included in m6anet? 
Also, I know '–num_iterations=NUM' is not a required option in m6anet inference, but how should I choose the iteration number if I want to set it? What does the iteration number mean? Also, did you set –num_iterations=NUM when generating supplementary table 6?

Thank you for your help!

**Comment by chrishendra93** [comment]
1. Yes this is done by default in m6anet inference
2. The default in the older version of m6Anet is 5 while in the latest release this is increased to 1000 for a more stable inference result. 
3. The HEK293T cell line is preprocessed and obtained from xPore paper. I did not re-basecall the sample and so the information should be available from the xPore paper https://www.nature.com/articles/s41587-021-00949-w

**Comment by kwonej0617** [comment]
Hi @chrishendra93 !

Thank you for your reply. Could you share your preprocessing data for HEK293T WT and KO rep1 data? If you have already deposited, could you share the link? 

Thank you so much!

**Comment by chrishendra93** [comment]
hi @kwonej0617 , the preprocessing data, ie, data.json is available through code ocean, the link is in the paper. Let me know if you have trouble with code ocean

Thanks!

**Comment by chrishendra93** [comment]
Hi @kwonej0617, this looks really different. Can I check with you the command that you used for running minimap2? Did you use the command that xPore used in the paper? (minimap2 ‘-ax map-ont -uf–secondary=no’). Also can you provide your readcount file?

**Comment by kwonej0617** [comment]
Hi, @chrishendra93 
Thank you for your reply! Yes. Basically, I referred to the command lines used in xPore.  

mmi files was generated as follows. 
```
minimap2 -ax map-ont -t 8 -uf -k14 -d Homo_sapiens.GRCh38.cdna.ncrna_wtChrIs_modified.mmi Homo_sapiens.GRCh38.cdna.ncrna_wtChrIs_modified.fa
```
Here is the minimap2 command line. (I used the command line from xpore manual)
Fastq file was downloaded. 
```
minimap2 -ax map-ont -uf -t 8 --secondary=no Homo_sapiens.GRCh38.cdna.ncrna_wtChrIs_modified.mmi HEK293T-WT-rep1.fastq.gz > HEK293T-WT-rep1.sam 2>> HEK293T-WT-rep1.sam.log
samtools view -Sb HEK293T-WT-rep1.sam | samtools sort -o HEK293T-WT-rep1.bam - &>>HEK293T-WT-rep1.bam.log
samtools index HEK293T-WT-rep1.bam &>> HEK293T-WT-rep1.bam.index.log
```

Here is data.readcount file for HEK293T-WT-rep1.
[data.readcount.gz](https://github.com/GoekeLab/m6anet/files/11011665/data.readcount.gz)

I appreciate your help!

**Comment by kwonej0617** [comment]
Hi @chrishendra93 
I just want to check if you had a chance to take a look my data.readcount.gz file.
I am thinking about which step makes a different result compared to yours. In the paper, I mentioned that you used nf-core-nanoseq. Looking at the pipeline of nf-core-nanoseq, it includes the quality control part. Do you think it would make different alignment results, generating different data.readcount.gz?

**Comment by chrishendra93** [comment]
hi @kwonej0617, apology for the delay as I have been packed with other stuffs as well. I will try to look through this over the weekend. Meanwhile, you can check Issue #96, it seems like it has more or less been resolved in there.
