### ISSUE TITLE
pip does not install latest version

### ISSUE THREAD

**Issue by mnsmar** [GoekeLab/m6anet#97]
Hi, on a fresh conda environment with either python 3.8 or 3.9, running `pip install m6anet` installs version 1.1.1 instead of 2.0.0.

Forcing `pip install m6anet==2.0.0` results in:

```
ERROR: Could not find a version that satisfies the requirement m6anet==2.0.0 (from versions: 0.0.2, 0.1.1, 1.0.0, 1.1.0, 1.1.1)
ERROR: No matching distribution found for m6anet==2.0.0
```

**Comment by chrishendra93** [comment]
hi @mnsmar  thanks for reporting this, there was an issue with the pypi package upload which I have just fixed with the release 2.0.1 Please try running pip install m6anet==2.0.1 or pip install m6anet which should install the latest version

**Comment by mnsmar** [comment]
Now on a fresh 3.9 it correctly attempts to install 2.0.1 but fails at the numpy installation. Seems like an incompatibility in the specified dependencies versions. They force numpy (1.17.3) which for some reason fails.

**Comment by Lucas-Servi** [comment]
I was having the same issue using python 3.10

I created a python=3.7.16 env using conda and it properly installed m6anet 2.0.1 without the numpy crash!

Hope it helps!

**Comment by chrishendra93** [comment]
Hi, seems like some of the required packages fail to install in python 3.9 and python 3.10. I don't think the numpy requirement is as strict but I've experienced problems with installing higher version of torch while the current one required by m6anet is not installable in python 3.10 (not sure about 3.9), I have to check this again before updating the setup files. Regardless for now please do a pip install on python 3.7 or python 3.8 environment

Thanks!

Best regards,

Christopher Hendra
