### ISSUE TITLE
Question about Fig1d in the paper

### ISSUE THREAD

**Issue by thadasps** [GoekeLab/m6anet#99]
Hi, I was wondering about the 5 model of epinano that you use to generate the ROC curve. Can you explain the different of Epinano1, 2, 3?. 

And I try to generate the ROC curve that I download the m6a sites dataset of m6ACE-seq that provided by xPore but I don't know I must use the start or end position to compare with m6A sites from m6Anet. Can you help or point me about this?

![image](https://user-images.githubusercontent.com/108725113/225706915-e4182767-735e-4ba3-8c9c-9d0522f895a8.png)

**Comment by chrishendra93** [comment]
hi @thadasps , These are just different models that EpiNano provide in their earlier version. For generating ROC curve, you should use the end position, but take care that you map the genomic position correctly (the reference annotations I have mentioned in issue [#96](https://github.com/GoekeLab/m6anet/issues/96) and you map the chromosome to the ucsc one (If I'm not mistaken the m6Ace chromosome uses ucsc annotation)
